name: Wired Brain Workflow

on:
  workflow_dispatch:
  push:
    branches: ['master']  # usually 'main' used but i have 'master' setup so leve as is for now

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore Dependencies
      run: dotnet restore
    
    # Build 
    - id: build
      name: Build      
      run: dotnet build --no-restore

    # Run Tests
    - id: test
      if: steps.build.outcome == 'success'
      name: Test
      run: dotnet test "WiredBrain.Tests/WiredBrain.Tests.csproj" --collect "XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura

    - id: coverage
      name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: WiredBrain.Tests/TestResults/**/coverage.cobertura.xml
        badge: false
        fail_below_min: false        
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: console
    
    # dotnet specific to run dotnetv publish command which bundle the compile application with its dependencies and output to its directory, ready to be deploy
    - id: publish
      name: Publish
      run: dotnet publish "WiredBrainApi.Web/WiredBrainApi.Web.csproj" -c Release -o ./publish --self-contained -r linux-x64 /p:UseAppHost=true
    # create zip archive of publish directory
    - name: Zip Artifact
      run: zip app.zip ./publish
    # retain zip file as build artifact
    - id: upload
      name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-webapp
        path: app.zip
    
    # Deploy steps to azure
    deploy:
    needs: build   # build when dependencies jobs (build) are completed successful
    runs-on: ubuntu-latest
    
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: dotnet-webapp        

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: app-wiredbrainapi
        package: app.zip        
      